# Generated by Django 4.0.1 on 2022-06-19 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('comment_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='PostLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, null=True, verbose_name='like')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_happy', models.BooleanField(default=False)),
                ('post_title', models.CharField(max_length=400, verbose_name='Title')),
                ('post_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='postImages', verbose_name='Image')),
                ('upload_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('likes', models.IntegerField(default=0, verbose_name='Number of Likes')),
            ],
            options={
                'verbose_name': "User's Post",
                'verbose_name_plural': "User's Post",
            },
        ),
<<<<<<< HEAD
        migrations.CreateModel(
            name='PostLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, null=True, verbose_name='like')),
                ('like_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Like Author')),
                ('post_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='userPosts.posts', verbose_name='Post id')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('comment_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userPosts.posts', verbose_name='Post')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Comment Author')),
            ],
        ),
=======
>>>>>>> af33d50 (Posts submitted by users are now saved to the backend)
    ]
