# Generated by Django 4.0.5 on 2022-06-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200, verbose_name='Title')),
                ('post_description', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Description')),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='postImages', verbose_name='Image')),
                ('upload_date', models.DateField(verbose_name='Date')),
                ('likes', models.IntegerField(verbose_name='Number of Likes')),
            ],
            options={
                'verbose_name': "User's Post",
                'verbose_name_plural': "User's Post",
            },
        ),
    ]
