# Generated by Django 4.0.1 on 2022-06-19 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userPosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlikes',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userPosts.posts', verbose_name='Post_id'),
        ),
    ]
