# Generated by Django 4.0.1 on 2022-06-19 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userPosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Post Author Username'),
        ),
        migrations.AddField(
            model_name='postlikes',
            name='like_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Like Author'),
        ),
        migrations.AddField(
            model_name='postlikes',
            name='post_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='userPosts.posts', verbose_name='Post id'),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Comment Author'),
        ),
        migrations.AddField(
            model_name='comments',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userPosts.posts', verbose_name='Post'),
        ),
    ]
