# Generated by Django 4.0.1 on 2022-06-19 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userPosts', '0002_alter_postlikes_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='likes',
        ),
        migrations.AlterField(
            model_name='postlikes',
            name='post_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='userPosts.posts', verbose_name='Post id'),
        ),
    ]
